baseURL = "https://ldgr.cassi.ba/"
languageCode = "en-us"
name = "Samuel Cassiba"
theme = "dream"

copyright = '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="CC-BY-NC-CA 4.0" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under the <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0">Attribution-NonCommercial-ShareAlike 4.0 International (CC-BY-NC-SA 4.0)</a> license.'

enableEmoji = true

disqusShortname = "ldgr-cassiba"

[params]
  author = "Samuel Cassiba"
  motto = "The ledger of Samuel Cassiba"
  avatar = "https://avatars0.githubusercontent.com/u/791892"

  email = "samuel@cassi.ba"
  github = "sbcas"
  linkedin = "scassiba"

  paginate = 4
  siteStartYear = 1984
